import type {
  GlassSettings,
  ColorSettings,
  GradientSettings,
  ExportFormat,
  ExportOptions,
  ColorRGB,
} from "@/types/glassmorphic";

// Helper to convert hex to RGB
function hexToRgb(hex: string): ColorRGB | null {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16),
      }
    : null;
}

// Adjust color for glass effect
function adjustColorForGlass(
  color: string,
  colorSettings: ColorSettings,
  intensity = 1.0,
): ColorRGB | null {
  const rgb = hexToRgb(color);
  if (!rgb) return null;

  const adjustedR = Math.round(rgb.r * colorSettings.brightness * intensity);
  const adjustedG = Math.round(rgb.g * colorSettings.brightness * intensity);
  const adjustedB = Math.round(rgb.b * colorSettings.brightness * intensity);

  return {
    r: Math.min(255, Math.max(0, adjustedR)),
    g: Math.min(255, Math.max(0, adjustedG)),
    b: Math.min(255, Math.max(0, adjustedB)),
  };
}

// ================== CSS EXPORTER ==================
export function exportToCSS(
  settings: GlassSettings,
  colorSettings: ColorSettings,
  gradientSettings: GradientSettings,
  inputColor: string,
  options: Partial<ExportOptions> = {},
): string {
  const { includeComments = true, componentName = "glass-card" } = options;

  const adjustedColor = adjustColorForGlass(inputColor, colorSettings);
  if (!adjustedColor) return "";

  let css = "";

  if (includeComments) {
    css += `/* Glassmorphism CSS - Generated by Glass Studio */\n\n`;
  }

  // Base glass styles
  if (gradientSettings.enabled) {
    const startRgb = adjustColorForGlass(
      gradientSettings.startColor,
      colorSettings,
      gradientSettings.intensity,
    );
    const endRgb = adjustColorForGlass(
      gradientSettings.endColor,
      colorSettings,
      gradientSettings.intensity,
    );

    if (startRgb && endRgb) {
      const gradientType =
        gradientSettings.type === "radial"
          ? "radial-gradient(circle"
          : `linear-gradient(${gradientSettings.direction}deg`;

      css += `.${componentName} {
  background: ${gradientType}, rgba(${startRgb.r}, ${startRgb.g}, ${startRgb.b}, ${colorSettings.opacity}) 0%, rgba(${endRgb.r}, ${endRgb.g}, ${endRgb.b}, ${colorSettings.opacity}) 100%);
  backdrop-filter: blur(${settings.blur}px);
  -webkit-backdrop-filter: blur(${settings.blur}px);
  border-radius: ${settings.borderRadius}px;
  border: 1px solid rgba(255, 255, 255, ${settings.borderOpacity});
  box-shadow: 
    0 8px 32px rgba(0, 0, 0, 0.1),
    inset 0 1px 0 rgba(255, 255, 255, 0.5),
    inset 0 -1px 0 rgba(255, 255, 255, 0.1),
    inset 0 0 ${settings.depth * 2}px ${settings.depth}px rgba(255, 255, 255, 0.1);
  position: relative;
  overflow: hidden;
}\n`;
    }
  } else {
    css += `.${componentName} {
  background: rgba(${adjustedColor.r}, ${adjustedColor.g}, ${adjustedColor.b}, ${colorSettings.opacity});
  backdrop-filter: blur(${settings.blur}px);
  -webkit-backdrop-filter: blur(${settings.blur}px);
  border-radius: ${settings.borderRadius}px;
  border: 1px solid rgba(255, 255, 255, ${settings.borderOpacity});
  box-shadow: 
    0 8px 32px rgba(0, 0, 0, 0.1),
    inset 0 1px 0 rgba(255, 255, 255, 0.5),
    inset 0 -1px 0 rgba(255, 255, 255, 0.1),
    inset 0 0 ${settings.depth * 2}px ${settings.depth}px rgba(255, 255, 255, 0.1);
  position: relative;
  overflow: hidden;
}\n`;
  }

  // Pseudo-elements for shine effect
  css += `
.${componentName}::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  height: 1px;
  background: linear-gradient(
    90deg,
    transparent,
    rgba(255, 255, 255, 0.8),
    transparent
  );
}

.${componentName}::after {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 1px;
  height: 100%;
  background: linear-gradient(
    180deg,
    rgba(255, 255, 255, 0.8),
    transparent,
    rgba(255, 255, 255, 0.3)
  );
}\n`;

  return css;
}

// ================== TAILWIND EXPORTER ==================
export function exportToTailwind(
  settings: GlassSettings,
  colorSettings: ColorSettings,
  gradientSettings: GradientSettings,
  inputColor: string,
  options: Partial<ExportOptions> = {},
): string {
  const { includeComments = true, componentName = "GlassCard" } = options;

  const adjustedColor = adjustColorForGlass(inputColor, colorSettings);
  if (!adjustedColor) return "";

  let output = "";

  if (includeComments) {
    output += `{/* Glassmorphism Tailwind Classes - Generated by Glass Studio */}\n\n`;
  }

  // Tailwind classes
  const blurClass =
    settings.blur >= 24
      ? "backdrop-blur-xl"
      : settings.blur >= 12
        ? "backdrop-blur-lg"
        : "backdrop-blur-md";
  const roundedClass =
    settings.borderRadius >= 24
      ? "rounded-3xl"
      : settings.borderRadius >= 16
        ? "rounded-2xl"
        : settings.borderRadius >= 12
          ? "rounded-xl"
          : "rounded-lg";

  output += `{/* Component: ${componentName} */}
<div className="${blurClass} ${roundedClass} border border-white/${Math.round(settings.borderOpacity * 100)} bg-white/${Math.round(colorSettings.opacity * 100)} shadow-xl relative overflow-hidden">
  {/* Your content here */}
</div>\n\n`;

  // Extended Tailwind config
  if (includeComments) {
    output += `{/* Add to tailwind.config.ts for custom values */}\n`;
  }

  output += `// tailwind.config.ts
module.exports = {
  theme: {
    extend: {
      backdropBlur: {
        'glass': '${settings.blur}px',
      },
      backgroundColor: {
        'glass': 'rgba(${adjustedColor.r}, ${adjustedColor.g}, ${adjustedColor.b}, ${colorSettings.opacity})',
      },
      borderRadius: {
        'glass': '${settings.borderRadius}px',
      },
      boxShadow: {
        'glass': '0 8px 32px rgba(0, 0, 0, 0.1), inset 0 1px 0 rgba(255, 255, 255, 0.5)',
      },
    },
  },
}\n`;

  return output;
}

// ================== CSS-IN-JS EXPORTER ==================
export function exportToCSSInJS(
  settings: GlassSettings,
  colorSettings: ColorSettings,
  gradientSettings: GradientSettings,
  inputColor: string,
  options: Partial<ExportOptions> = {},
): string {
  const { includeComments = true, componentName = "GlassCard" } = options;

  const adjustedColor = adjustColorForGlass(inputColor, colorSettings);
  if (!adjustedColor) return "";

  let output = "";

  if (includeComments) {
    output += `// Glassmorphism styled-components - Generated by Glass Studio\n\n`;
  }

  output += `import styled from 'styled-components';\n\n`;

  let backgroundValue: string;
  if (gradientSettings.enabled) {
    const startRgb = adjustColorForGlass(
      gradientSettings.startColor,
      colorSettings,
      gradientSettings.intensity,
    );
    const endRgb = adjustColorForGlass(
      gradientSettings.endColor,
      colorSettings,
      gradientSettings.intensity,
    );

    if (startRgb && endRgb) {
      const gradientType =
        gradientSettings.type === "radial"
          ? "radial-gradient(circle"
          : `linear-gradient(${gradientSettings.direction}deg`;
      backgroundValue = `\${gradientType}, rgba(\${startRgb.r}, \${startRgb.g}, \${startRgb.b}, \${colorSettings.opacity}) 0%, rgba(\${endRgb.r}, \${endRgb.g}, \${endRgb.b}, \${colorSettings.opacity}) 100%)`;
    } else {
      backgroundValue = `rgba(${adjustedColor.r}, ${adjustedColor.g}, ${adjustedColor.b}, ${colorSettings.opacity})`;
    }
  } else {
    backgroundValue = `rgba(${adjustedColor.r}, ${adjustedColor.g}, ${adjustedColor.b}, ${colorSettings.opacity})`;
  }

  output += `export const ${componentName} = styled.div\`
  background: ${backgroundValue};
  backdrop-filter: blur(${settings.blur}px);
  -webkit-backdrop-filter: blur(${settings.blur}px);
  border-radius: ${settings.borderRadius}px;
  border: 1px solid rgba(255, 255, 255, ${settings.borderOpacity});
  box-shadow: 
    0 8px 32px rgba(0, 0, 0, 0.1),
    inset 0 1px 0 rgba(255, 255, 255, 0.5),
    inset 0 -1px 0 rgba(255, 255, 255, 0.1),
    inset 0 0 ${settings.depth * 2}px ${settings.depth}px rgba(255, 255, 255, 0.1);
  position: relative;
  overflow: hidden;

  &::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 1px;
    background: linear-gradient(
      90deg,
      transparent,
      rgba(255, 255, 255, 0.8),
      transparent
    );
  }

  &::after {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 1px;
    height: 100%;
    background: linear-gradient(
      180deg,
      rgba(255, 255, 255, 0.8),
      transparent,
      rgba(255, 255, 255, 0.3)
    );
  }
\`;\n`;

  return output;
}

// ================== SCSS EXPORTER ==================
export function exportToSCSS(
  settings: GlassSettings,
  colorSettings: ColorSettings,
  gradientSettings: GradientSettings,
  inputColor: string,
  options: Partial<ExportOptions> = {},
): string {
  const { includeComments = true, componentName = "glass-card" } = options;

  const adjustedColor = adjustColorForGlass(inputColor, colorSettings);
  if (!adjustedColor) return "";

  let output = "";

  if (includeComments) {
    output += `// Glassmorphism SCSS Variables - Generated by Glass Studio\n\n`;
  }

  // SCSS Variables
  output += `// Glass Variables
$glass-blur: ${settings.blur}px;
$glass-refraction: ${settings.refraction};
$glass-depth: ${settings.depth}px;
$glass-border-radius: ${settings.borderRadius}px;
$glass-border-opacity: ${settings.borderOpacity};
$glass-color-opacity: ${colorSettings.opacity};
$glass-color-r: ${adjustedColor.r};
$glass-color-g: ${adjustedColor.g};
$glass-color-b: ${adjustedColor.b};

// Gradient Variables
$glass-gradient-enabled: ${gradientSettings.enabled};
$glass-gradient-start: ${gradientSettings.startColor};
$glass-gradient-end: ${gradientSettings.endColor};
$glass-gradient-direction: ${gradientSettings.direction}deg;
$glass-gradient-type: ${gradientSettings.type};

// Mixin
@mixin glass-effect {
  background: rgba($glass-color-r, $glass-color-g, $glass-color-b, $glass-color-opacity);
  backdrop-filter: blur($glass-blur);
  -webkit-backdrop-filter: blur($glass-blur);
  border-radius: $glass-border-radius;
  border: 1px solid rgba(255, 255, 255, $glass-border-opacity);
  box-shadow: 
    0 8px 32px rgba(0, 0, 0, 0.1),
    inset 0 1px 0 rgba(255, 255, 255, 0.5),
    inset 0 -1px 0 rgba(255, 255, 255, 0.1),
    inset 0 0 ($glass-depth * 2) $glass-depth rgba(255, 255, 255, 0.1);
  position: relative;
  overflow: hidden;

  &::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 1px;
    background: linear-gradient(
      90deg,
      transparent,
      rgba(255, 255, 255, 0.8),
      transparent
    );
  }

  &::after {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 1px;
    height: 100%;
    background: linear-gradient(
      180deg,
      rgba(255, 255, 255, 0.8),
      transparent,
      rgba(255, 255, 255, 0.3)
    );
  }
}

// Usage
.${componentName} {
  @include glass-effect;
}\n`;

  return output;
}

// ================== UNIVERSAL EXPORTER ==================
export function exportGlass(
  format: ExportFormat,
  settings: GlassSettings,
  colorSettings: ColorSettings,
  gradientSettings: GradientSettings,
  inputColor: string,
  options: Partial<ExportOptions> = {},
): string {
  switch (format) {
    case "css":
      return exportToCSS(
        settings,
        colorSettings,
        gradientSettings,
        inputColor,
        options,
      );
    case "tailwind":
      return exportToTailwind(
        settings,
        colorSettings,
        gradientSettings,
        inputColor,
        options,
      );
    case "css-in-js":
      return exportToCSSInJS(
        settings,
        colorSettings,
        gradientSettings,
        inputColor,
        options,
      );
    case "scss":
      return exportToSCSS(
        settings,
        colorSettings,
        gradientSettings,
        inputColor,
        options,
      );
    default:
      return exportToCSS(
        settings,
        colorSettings,
        gradientSettings,
        inputColor,
        options,
      );
  }
}

export const exportFormats: {
  id: ExportFormat;
  name: string;
  extension: string;
  icon: string;
}[] = [
  { id: "css", name: "Plain CSS", extension: ".css", icon: "FileCode" },
  { id: "tailwind", name: "Tailwind CSS", extension: ".tsx", icon: "Wind" },
  {
    id: "css-in-js",
    name: "styled-components",
    extension: ".tsx",
    icon: "Braces",
  },
  { id: "scss", name: "SCSS/Sass", extension: ".scss", icon: "Hash" },
];
